#![allow(dead_code)]
#![allow(redundant_semicolons)]

pub enum TokenTypes {
    // Keywords
    KeywordFn,
    KeywordImmut,
    KeywordHeap,
    KeywordFree,
    KeywordReturn,
    KeywordConstruct,
    KeywordIf,
    KeywordElse,
    KeywordFor,
    KeywordWhile,
    KeywordBreak,
    KeywordContinue,
    KeywordImport,
    KeywordAsync,
    KeywordAwait,
    KeywordCase,
    KeywordEnum,
    KeywordClass,
    KeywordStruct,
    KeywordOut,
    KeywordIsOk,
    KeywordIsErr,
    // Identifiers & Literals
    Identifier,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    CharLiteral,
    BooleanLiteral,
    // Operators & Symbols
    OperatorPlus,
    OperatorMinus,
    OperatorStar,
    OperatorSlash,
    OperatorPercent,
    OperatorAssign,
    OperatorEqual,
    OperatorNotEqual,
    OperatorLess,
    OperatorGreater,
    OperatorLessEqual,
    OperatorGreaterEqual,
    OperatorAnd,
    OperatorOr,
    OperatorNot,
    OperatorDot,
    // Punctuation
    ParenOpen,
    ParenClose,
    BraceOpen,
    BraceClose,
    BracketOpen,
    BracketClose,
    Comma,
    Colon,
    Semicolon,
    // Special Tokens
    CommentSingle,
    CommentBlock,
    EOF,
    Unknown,
}